services:
  postgres:
    image: 'postgis/postgis:17-3.5'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    labels:
      org.springframework.boot.service-connection: postgres
