[versions]
mockito = "5.21.0"
jjwt = "0.13.0"

[libraries]
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
jjwt-api = { group = "io.jsonwebtoken", name = "jjwt-api", version.ref = "jjwt" }
jjwt-impl = { group = "io.jsonwebtoken", name = "jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { group = "io.jsonwebtoken", name = "jjwt-jackson", version.ref = "jjwt" }
